### ISSUE TITLE
update dependencies in conda-forge feedstock

### ISSUE THREAD

**Issue by CagtayFabry** [asdf-format/asdf#1096]
With the recent releases the conda-forge recipe over at https://github.com/conda-forge/asdf-feedstock has become slightly out of sync with regard to the package dependencies leading to some possible broken installs (see https://github.com/asdf-format/asdf-standard/issues/301)

The requirements in [meta.yaml](https://github.com/conda-forge/asdf-feedstock/blob/master/recipe/meta.yaml#L19-L33)
```yaml
requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - pyyaml >=3.10
    - jmespath >=0.6.2
    - Jsonschema >=3.0.2,<4
    - numpy >=1.10
    - semantic_version >=2.8
    - importlib_resources >=3
    - packaging >=16.0
```
are not up to date with the release metadata
https://github.com/asdf-format/asdf/blob/3483bfe273205eac39ca20097b2af7a27a3283be/setup.cfg#L24-L37

when working with conda recipes we have made good experience with including `pip check` as a simple test step in `meta.yaml` to make sure the install covers the requirements of the python package, see [here](https://github.com/conda-forge/weldx-feedstock/blob/612f94c315a11bb1e4c7f6122ba0a693440e6864/recipe/meta.yaml#L41-L50) for an example
