### ISSUE TITLE
Invalid test.asdf files in the RTD documenation

### ISSUE THREAD

**Issue by KenMighell** [asdf-format/asdf#1110]
Many (most? all?) of the result test.asdf files shown in the readthedocs.io (RTD) documentation are not valid ASDF files using asdf 2.10.1 .

The "Hello World" example at  
https://asdf.readthedocs.io/en/stable/asdf/overview.html#hello-world  
```
from asdf import AsdfFile

# Make the tree structure, and create a AsdfFile from it.
tree = {'hello': 'world'}
ff = AsdfFile(tree)
ff.write_to("test.asdf")

# You can also make the AsdfFile first, and modify its tree directly:
ff = AsdfFile()
ff.tree['hello'] = 'world'
ff.write_to("test.asdf")
```
produces the following test.asdf file 
```
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 2.10.1}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.10.1}
hello: world
...
```
using asdf 2.10.1 and Python 3.9.7.

The RTD documentation gives this result
```
test.asdfb'#ASDF' 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: Space Telescope Science Institute, homepage: 'http://github.com/spacetelescope/asdf',
  name: asdf, version: 2.7.5}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.7.5}
hello: world
...
```

The asdftool issues this error  
ValueError: Input object does not appear to be an ASDF file or a FITS with ASDF extension  
with the current RTD version of test.asdf.

This is not surprising given that the current RTD version of test.asdf starts with this line:  
```test.asdfb'#ASDF' 1.5.0```
