### ISSUE TITLE
Metadata don't distinguish between Fortran- and C-order arrays?

### ISSUE THREAD

**Issue by bilderbuchi** [asdf-format/asdf#1205]
I am confused how the metadata seems to not indicate if an array is stored in column- or row-major order.
Based on #538, and triggered by [this HackerNews comment](https://news.ycombinator.com/item?id=33092662), I came up with this example:
```python
import numpy as np
import asdf

farray = np.array([[11,12,13], [21,22,23]], order='F')
carray = np.array([[11,12,13], [21,22,23]], order='C')
file = asdf.AsdfFile({"farray": farray, "carray": carray})
file.write_to("strides.asdf")

file2 = asdf.open("strides.asdf")

farray2 = file2.tree["farray"]
print("Original farray:\n", farray[:,:])
print("Recovered farray:\n", farray2[:,:])
carray2 = file2.tree["carray"]
print("Original carray:\n", carray[:,:])
print("Recovered carray:\n", carray2[:,:])
```
which, when running with current asdf from conda, successfully recovers the arrays correctly:
```
Original farray:
 [[11 12 13]
 [21 22 23]]
Recovered farray:
 [[11 12 13]
 [21 22 23]]
Original carray:
 [[11 12 13]
 [21 22 23]]
Recovered carray:
 [[11 12 13]
 [21 22 23]]
```

However, the header of the created file shows no indication that those two arrays have different order:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 2.13.0}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.13.0}
carray: !core/ndarray-1.0.0
  source: 0
  datatype: int32
  byteorder: little
  shape: [2, 3]
farray: !core/ndarray-1.0.0
  source: 2
  datatype: int32
  byteorder: little
  shape: [2, 3]
...
```
How can this successfully round-trip arrays if the row/column-major information is not contained in the metadata? Is this using some numpy-specific thing (cf #827) when saving the contents to disk?

From [the standard](https://asdf.readthedocs.io/en/stable/asdf/arrays.html?highlight=strides#sharing-of-data), assuming it's _stored_ in C order, I would have expected that the F-array would have gotten a `strides` entry. 
If it's actually stored in F-order, how is a loading program able to determine that?
If the data is not stored in the order in which it was presented to asdf, does that have performance implications?

I didn't know if this is a standards-related issue or one of the Python implementation.
