### ISSUE TITLE
Add option to disable inline representation when writing to ASDF file

### ISSUE THREAD

**Issue by ketozhang** [asdf-format/asdf#1499]
I do not see this in the docs, but currently when writing to ASDF file, all ASDF tags are written inline if it is not nested (i.e., all children are leaf nodes).

**Current Behavior:**
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 2.14.3}
```

**Desired Behavior:**
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 
  author: The ASDF Developers
  homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, 
  version: 2.14.3
```
---

Can we add an option to disable this and I much prefer this to be the default.

**Comment by ketozhang** [comment]
Here's an example what happens if the tagged field has a child field

```yaml
node: !<asdf://example.com/tags/node-1.0.0>
  child: !<asdf://example.com/tags/node-1.0.0> {child: null}
```

This looks a bit silly

**Comment by WilliamJamieson** [comment]
This should be controlled by the `flowStyle` setting in the schema describing the tag. See https://asdf-standard.readthedocs.io/en/1.5.0/schemas/yaml_schema.html#Schema%20Definitions for details. Not that in your case I believe you need to set `flowStyle: block` in the schema.

It should work as the Roman asdf files make extensive use of this. For example if one generates and saves a `wfi_image`, its schema contains `flowStyle: block` [here](https://github.com/spacetelescope/rad/blob/d95148813bb26460544a218317fdb05fe8c1cd29/src/rad/resources/schemas/wfi_image-1.0.0.yaml#L176). A sample header is:
```yaml
roman: !<asdf://stsci.edu/datamodels/roman/tags/wfi_image-1.0.0>
  meta:
    aperture: !<asdf://stsci.edu/datamodels/roman/tags/aperture-1.0.0>
      name: WFI_06_FULL
      position_angle: 30.149604523080143
    cal_step: !<asdf://stsci.edu/datamodels/roman/tags/cal_step-1.0.0>
      assign_wcs: INCOMPLETE
      flat_field: SKIPPED
      dark: COMPLETE
      dq_init: COMPLETE
      jump: COMPLETE
      linearity: SKIPPED
      photom: COMPLETE
      ramp_fit: COMPLETE
      saturation: INCOMPLETE
    calibration_software_version: !<asdf://stsci.edu/datamodels/roman/tags/calibration_software_version-1.0.0> Version
      94bb92d0a922867c94ed1fddcb4216a5
    coordinates: !<asdf://stsci.edu/datamodels/roman/tags/coordinates-1.0.0>
      reference_frame: ICRS
    crds_context_used: roman_8226.pmap
    crds_software_version: 63.1.67
    ephemeris: !<asdf://stsci.edu/datamodels/roman/tags/ephemeris-1.0.0>
      earth_angle: 1.301915411283766
      moon_angle: 1.1516403400836825
      sun_angle: 2.736255246678112
      type: PREDICTED
      time: 59865.65463414276
      ephemeris_reference_frame: Frame 3706a1f3
      spatial_x: -1.3623950365305825e+308
      spatial_y: -1.60804538172114e+306
      spatial_z: 1.5921914973582028e+307
      velocity_x: 1.3125923623238684e+308
      velocity_y: -1.6632717836035864e+308
      velocity_z: 2.352229275461757e+307
```
I believe yaml would have normally chosen to represent the part under `aperture` in the way you describe if the schemas involved did not specify the `flowStyle: block`.
