### ISSUE TITLE
Consider option for allowing more graceful loading of files with failed conversions

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1555]
For files that contain portions of invalid data (such as those generated with out-of-date extensions or older unsupported versions) it might be helpful to have an option to allow failed conversions (and pass through raw values for those failed conversions).

Attempting to open the following invalid example file:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 3.0.0.dev265+g0c44742c}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension._manifest.ManifestExtension
    extension_uri: asdf://asdf-format.org/core/extensions/core-1.5.0
    software: !core/software-1.0.0 {name: asdf-astropy, version: 0.3.0}
a: [1, 2, 3]
q: !unit/quantity-1.1.0 {datatype: float64, missing_unit: True}
...
```

results in ```KeyError: 'value'``` (as the quantity is invalid, note that does require disabling `validate_on_read` to skip the failure caused by the invalid yaml).

However a user might want to read `a` in the above example. For the above example reading the text would be one option but if `a` were more complicated (for example an array with the data contained in a block) reading the value from the text might not be possible.

This came up when @schlafly attempted to extract data from a ROMAN file generated with older versions of the ROMAN software.
