### ISSUE TITLE
`asdf.util.load_yaml` fails on recursive object

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1821]
# Description of the problem

Attempting to read an asdf file with a recursive reference using `asdf.util.load_yaml` fails with `ConstructorError: found unconstructable recursive node`.

# Example of the problem

```python
import asdf
d = {}
d['a'] = d
asdf.AsdfFile(d).write_to("recursive.asdf")
asdf.util.load_yaml("recursive.asdf")
```
Produces:
```
ConstructorError: found unconstructable recursive node
```

Note that passing `tagged=True` is a work-around for the above issue (as it triggers using the `AsdfLoader` which handles the recursion).

# System information

asdf version: main
python version: 3.10
operating system: osx

**Comment by braingram** [comment]
This error was seen when attempting to use `load_yaml` on a jwst NIRSPEC file (due to some structure in the wcs).

This is sufficient to produce the error:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.6.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
o: &id001 !transform/remap_axes-1.4.0
  inputs: [x0, x1]
  inverse: !transform/remap_axes-1.4.0
    inputs: [x0, x1, x2]
    inverse: *id001
    mapping: [2, 1]
    outputs: [x0, x1]
  mapping: [0, 1, 0]
  outputs: [x0, x1, x2]
...
```
