### ISSUE TITLE
validate_datatype raises instead of yield preventing some schema combiner usage

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1903]
The use of `raise` (for example):
https://github.com/asdf-format/asdf/blob/9d7ff2eb446a220639e2aa6a84386ea50348d205/asdf/tags/core/ndarray.py#L529
in `validate_datatype` can lead to incorrect validation errors when used within a schema combiner. A schema containing:
```yaml
anyOf:
  - tag: tag:stsci.edu:asdf/core/ndarray-1.*
    datatype: float64
  - "null"
```
Fails for `None` values with `ValidationError: Not an array`.
