### ISSUE TITLE
Recursive reference breaks `asdftool diff`

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1914]
With file `recursive.asdf`:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.6.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
d: &id001
  d2: *id001
...
```

`asdftool diff recursive.asdf recursive.asdf` results in:

```
ERROR:root:maximum recursion depth exceeded while calling a Python object
```
