### ISSUE TITLE
asdf fails to load file with tags from multiple standards

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1916]
The standard isn't clear on what is [meant by](https://www.asdf-format.org/projects/asdf-standard/en/1.1.1/versioning.html#handling-version-mismatches):
> Writing out a file that mixes versions of schema from different versions of the ASDF standard is not recommended, though such a file should be accepted by readers given the rules above.

Using the following file which contains tags from 1.5.0 and 1.6.0:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.6.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
i0: !core/integer-1.1.0
  sign: +
  string: '1'
  words: !core/ndarray-1.1.0
    data: [1]
i1: !core/integer-1.0.0
  sign: +
  string: '1'
  words: !core/ndarray-1.0.0
    data: [1]
...
```

The file opens with a few warnings:
```
tag:stsci.edu:asdf/core/ndarray-1.0.0 is not recognized, converting to raw Python data structure
tag:stsci.edu:asdf/core/integer-1.0.0 is not recognized, converting to raw Python data structure
```
and `i1` is a `TaggedDict` whereas `i0` is an `IntegerType`.

If "should be accepted by readers given the rules above" means that `i1` should be an `IntegerType` then asdf is not following the standard.
