### ISSUE TITLE
Inconsistency between ASDF standard and the implementation

### ISSUE THREAD

**Issue by vmarkovtsev** [asdf-format/asdf#709]
(I am working on an ASDF reader in Go)

According to the definition of [extension_metadata](https://asdf-standard.readthedocs.io/en/latest/generated/stsci.edu/asdf/core/extension_metadata-1.0.0.html),
any object of that type must contain two properties:

- extension_class
- package of type `software`

However, this is what I get with the following code:

```python
asdf.AsdfFile().write_to("test.asdf")
```

```
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: {name: asdf, version: 2.4.2}
```

The property is named "software" instead of "package" and does not contain a tag.
