### ISSUE TITLE
Add weldx to downstream workflow?

### ISSUE THREAD

**Issue by eslavich** [asdf-format/asdf#946]
@CagtayFabry we have an actions workflow in this repository that runs ASDF-related tests in a handful of our downstream projects.  We run this workflow on a regular schedule and also immediately prior to release, to make sure we're not about to break something.  Are you interested in having weldx added to the list?  If so, can you confirm that this is a reasonable test script:

```
git clone https://github.com/BAMWelDX/weldx.git
cd weldx
conda env create -f environment.yml
conda activate weldx
pytest tests/asdf_tests
```

**Comment by CagtayFabry** [comment]
Thanks for the notification and good to know about downstream tests @eslavich 💯 
definitely interested, I will get back to you in more detail in a few days

We will have to check if running `pytest tests/asdf_tests` is sufficient (it should be).

we will probably remove `environment.yml` soon, I think something like the following should work (and be faster)

```yaml
runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install asdf
        run: pip install git+https://github.com/asdf-format/asdf@${{ github.event.inputs.asdf_ref || 'master' }}
      - name: Install pytest
        run: pip install pytest pytest-cov pytest-xdist setuptools_scm
      - name: Install weldx
        run: | 
          git clone https://github.com/BAMWelDX/weldx.git
          cd weldx
          pip install -e .
      - name: Run weldx tests
        run: pytest tests/asdf_tests --asdf-tests
```

Maybe it would be possible to test the current `asdf` master against both, the current `weldx` master (for our development) as well as our latest pypi release (for stability).

also 🔔  @vhirtham @marscher
