### ISSUE TITLE
how to read/resolve cyclic referencens in custom code

### ISSUE THREAD

**Issue by CagtayFabry** [asdf-format/asdf#974]
I am trying to resolve cyclic dependencies in some custom classes but get stuck upon encountering `PendingValue` when reading the created ASDF files
What is the correct way to resolve `PendingValue` in custom code?

### example
A super simple ring dependency (see definitions below):

```python
@dataclass
class RefClass:
    name: str
    ref: RefClass = None

a = RefClass(name="first")
b = RefClass(name="second")
a.ref = b
b.ref = a
```
This looks as expected when creating the ASDF file:
```yaml
a: &id001 !<tag:weldx.bam.de:weldx/RefClass-1.0.0>
  name: first
  ref: &id002 !<tag:weldx.bam.de:weldx/RefClass-1.0.0>
    name: second
    ref: *id001
b: *id002
```

However the links do not get resolved in `from_tree` and I end up with `PendingValue` on read
```python
'a': RefClass(name='first', ref=RefClass(name='second', ref=PendingValue)),
'b': RefClass(name='second', ref=PendingValue)
```

I tried digging around in `ctx._tree_modification_context._map` and `ctx._tree_modification_context._pending` from the `from_tree`  method (which looked promising) but cannot figure out how to get the correct references from the `PendingValue` objects

Any examples or hints on where to look?

#### classes / schema
```python
class RefClassTypeASDF(WeldxType):

    name = "RefClass"
    version = "1.0.0"
    types = [RefClass]
    requires = ["weldx"]

    @classmethod
    def to_tree(cls, node: RefClass, ctx):
        """convert to python dict"""
        return node.__dict__

    @classmethod
    def from_tree(cls, tree, ctx):
        """Reconstruct form tree."""
        return RefClass(**tree)
```

```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
id: "http://weldx.bam.de/schemas/weldx/RefClass-1.0.0"
tag: "tag:weldx.bam.de:weldx/RefClass-1.0.0"

title: |
  A clyclic class

type: object
properties:
  name:
    type: string
  ref:
    tag: "tag:weldx.bam.de:weldx/RefClass-1.0.0"
...
```
